export const COLORS = [
  {
    bg: "bg-[#FFF6FD]",
    border: "border-[#FF9FEA]",
    hover: "hover:bg-[#FFD5F6]",
    icon: "bg-[#FF81E4]",
    fill: "group-hover:fill-[#FF81E4]",
  },
  {
    bg: "bg-[#F6FCFF]",
    border: "border-[#94DBFF]",
    hover: "hover:bg-[#D7F2FF]",
    icon: "bg-[#71D0FF]",
    fill: "group-hover:fill-[#71D0FF]",
  },
  {
    bg: "bg-[#FFFFF6]",
    border: "border-[#FFCD07]",
    hover: "hover:bg-[#FFF6D1]",
    icon: "bg-[#FFCD07]",
    fill: "group-hover:fill-[#FFCD07]",
  },
  {
    bg: "bg-[#F9F4FF]",
    border: "border-[#C492FF]",
    hover: "hover:bg-[#EFD9FF]",
    icon: "bg-[#BB81FF]",
    fill: "group-hover:fill-[#BB81FF]",
  },
  {
    bg: "bg-[#FFFFF6]",
    border: "border-[#FFCD07]",
    hover: "hover:bg-[#FFF6D1]",
    icon: "bg-[#FFCD07]",
    fill: "group-hover:fill-[#FFCD07]",
  },
  {
    bg: "bg-[#FFF4F4]",
    border: "border-[#FF9999]",
    hover: "hover:bg-[#FFDFDF]",
    icon: "bg-[#FF7B7B]",
    fill: "group-hover:fill-[#FF7B7B]",
  },
  {
    bg: "bg-[#F6FCFF]",
    border: "border-[#94DBFF]",
    hover: "hover:bg-[#D7F2FF]",
    icon: "bg-[#71D0FF]",
    fill: "group-hover:fill-[#71D0FF]",
  },
  {
    bg: "bg-[#F7FFF6]",
    border: "border-[#A6FF9B]",
    hover: "hover:bg-[#D6FFD1]",
    icon: "bg-[#58F544]",
    fill: "group-hover:fill-[#58F544]",
  },
];